# Generated by Django 4.2.6 on 2023-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20231016_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='John Doe', max_length=255)),
                ('nick_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_year_in_college', models.IntegerField()),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('year_joined_club', models.IntegerField()),
                ('club_position', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
